[versions]
agp = "8.3.1"
appcompat = "1.6.1"
constraintlayout = "2.1.4"
coreKtx = "1.12.0"
fresco = "3.1.3"
kotlin = "1.9.23"
material = "1.11.0"
recyclerview = "1.3.2"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
fresco-animated-base = { module = "com.facebook.fresco:animated-base", version.ref = "fresco" }
fresco-animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
fresco-webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }
google-android-material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
#android-application = { module = "com.android.application", version.ref = "agp" }
#jetbrains-kotlin-android = { module = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
#jetbrains-kotlin-parcelize = { module = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
